baseURL = 'https://mattchan.me/'
languageCode = 'en-us'
title = 'Community Notes'
theme = 'hugo-bearblog'
author = 'Matt Chan'

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"
